default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: sweet_potato
  username: sweet_potato
  password: Y~wU*b6@7y92a

test:
  <<: *default
  database: sweet_potato_test
  username: sweet_potato
  password: Y~wU*b6@7y92a

production:
  <<: *default
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']