base: &base
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  host: localhost

development:
  <<: *base
  database: sweet_potato
  username: sweet_potato
  password: Y~wU*b6@7y92a

test:
  <<: *base
  database: pae_test
  username: root
  password:

# remote_development:
#   <<: *base
#   database: sweet_potato_dev
#   username: <%= Rails.application.secrets.db_user %>
#   password: <%= Rails.application.secrets.db_pass %>

# stage:
#   <<: *base
#   database: sweet_potato
#   username: <%= Rails.application.secrets.db_user %>
#   password: <%= Rails.application.secrets.db_pass %>

production:
  <<: *base
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORDs']